theme: jekyll-theme-minimal
title: "Welcome to Julia Thompson's homepage"

navbar:
  title: "Julia Thompson"
  left:
    - text: "Research"
      href: research.html
    - text: "Teaching"
      href: teaching.html
    - text: "Programming"
      href: software.html

  right:
    - icon: fa-envelope fa-lg
      href: contact.html
    - icon: fa-github fa-lg
      href: https://github.com/Julia-Thompson
    - icon: fa-linkedin fa-lg
      href: https://www.linkedin.com/in/julia-mink
output:
  html_document:
    theme: paper
    css: 'styles.css'
