##

# Teaching

<br>


#### Environmental Economics <span style="color:gray"> <font size="4"> - Professor </font> </span>
University of Bonn, Graduate course, Summer 2023 & Summer 2025
<br><br>


#### Introduction to Econometrics <span style="color:gray"> <font size="4"> - Professor </font> </span>
University of Bonn, Undergraduate course, Winter 2022
<br><br>

#### Public Economics <span style="color:gray"> <font size="4"> - Lecturer </font> </span>
Sciences Po School of Public Affairs, Graduate course, Fall 2020 & Fall 2021
<br><br>

#### Principles of micro- and macroeconomics <span style="color:gray"> <font size="4"> - Graduate Student Instructor </font> </span>
Sciences Po, Undergraduate course, Fall 2017 & Fall 2018, Professors Yann Algan and Guillaume Plantin

***

#### Trade and International Finance <span style="color:gray"> <font size="4"> - Teaching assistant </font> </span>
Sciences Po, Undergraduate course, Spring 2021, Professor Philippe Martin
<br><br>

#### Perspectives in Economics and Sociology <span style="color:gray"> <font size="4"> - Teaching assistant </font> </span>
Sciences Po, Undergraduate course, Spring 2021, Professors Roberto Galbiati and Mirna Safi
<br><br>

#### Principles of micro- and macroeconomics <span style="color:gray"> <font size="4"> - Coordinator & Teaching assistant </font> </span>
Sciences Po, Undergraduate course, Fall 2019 & Fall 2020, Professors Yann Algan, Kerstin Holzheu and Jeanne Commault
Coordination between tutors, professors, administration, teaching assistance
<br><br>

#### The Economics of the Media:  A Global Perspective <span style="color:gray"> <font size="4"> - Teaching assistant </font> </span>
Sciences Po, Graduate course, Fall 2018, Professor Julia Cagé

